dist: trusty

sudo: required

language: ruby

services:
  - docker

env:
  matrix:
          - TYPE=pmemkv-abf1c488a457fa21ba628fb5b08d6418e58e37e7 OS=ubuntu OS_VER=19.04
          - TYPE=pmemkv-0.8 OS=ubuntu OS_VER=19.04
before_install:
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - export GITHUB_REPO=pmem/pmemkv-ruby
  - export DOCKERHUB_REPO=pmem/pmemkv-ruby
  - cd utils/docker
  - ./pull-or-rebuild-image.sh
  - if [[ -f push_image_to_repo_flag ]]; then PUSH_THE_IMAGE=1; fi
  - if [[ -f skip_build_package_check ]]; then export SKIP_CHECK=1; fi
  - rm -f push_image_to_repo_flag skip_build_package_check

script:
  - ./build.sh

after_success:
  - if [[ $PUSH_THE_IMAGE -eq 1 ]]; then images/push-image.sh $OS-$OS_VER; fi
